---

- name: Install pgbouncer
  yum:
    name: pgbouncer
    state: present
  tags: ["install"]

- name: Install pgbouncer-redirect script
  template:
    src: pgbouncer-redirect.tmpl
    dest: "{{ pgbouncer_redirect_script }}"
    owner: root
    group: root
    mode: 0755
  when: pgbouncer_redirect_install | bool

- name: Copy SSL certs to pgbouncer
  copy:
    src: "{{ item.src }}"
    remote_src: true
    dest: "{{ item.dest }}"
    owner: pgbouncer
    group: pgbouncer
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - src: "{{ pgbouncer_ssl_ca_path }}"
      dest: "/etc/pgbouncer/ca.crt"
    - src: "{{ pgbouncer_ssl_cert_path }}"
      dest: "/etc/pgbouncer/pgbouncer.crt"
    - src: "{{ pgbouncer_ssl_private_key_path }}"
      dest: "/etc/pgbouncer/pgbouncer.key"
  notify: restart pgbouncer
  when: pgbouncer_ssl_enable | bool

- name: Configure pgbouncer databases
  template:
    src: databases.ini.j2
    dest: "{{ pgbouncer_database_ini }}"
    owner: "{{ 'pgbouncer' if pgbouncer_redirect_install else 'root' }}"
    group: pgbouncer
    mode: 0640
  notify: reload pgbouncer

- name: Configure pgbouncer
  template:
    src: pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    owner: root
    group: pgbouncer
    mode: 0640
  notify: reload pgbouncer
  when: pgbouncer_instances | int == 1

- name: Add pgbouncer user list
  template:
    src: userlist.txt.j2
    dest: /etc/pgbouncer/userlist.txt
    owner: root
    group: pgbouncer
    mode: 0640
  notify: reload pgbouncer

- name: Setup multiple instances
  include_tasks: setup_multiple_instances.yml
  when: pgbouncer_instances | int > 1

- name: Enable and start single pgbouncer instance
  systemd:
    name: pgbouncer
    state: started
    enabled: true
  when: pgbouncer_instances | int == 1

- name: Enable and start pgbouncer instances
  systemd:
    name: "pgbouncer@{{ item }}"
    state: started
    enabled: true
  loop: "{{ range(1, (pgbouncer_instances | int) + 1) | list }}"
  when: pgbouncer_instances | int > 1

- name: Configure firewall
  include_tasks: firewall.yml
  tags: ["firewall"]
