---

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "ol8-single"
    image: "oraclelinux:8"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups: ["single"]

  - name: "ol8-multiple"
    image: "oraclelinux:8"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups: ["multiple"]
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        pgbouncer_allow_sources:
          - "10.0.10.11"
          - "10.0.10.12"
          - "10.0.10.13"
      single:
        pgbouncer_instances: 1
      multiple:
        pgbouncer_instances: 3
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
